### ISSUE TITLE
Lack of LICENSE file

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/fabian#22]
I've noticed that fabian doesn't have a LICENSE file. In `setup.py` it's mentioned that fabian is under GPL?

**Comment by jonwright** [comment]
Seems @ebknudsen put this in the setup.py in 2006, so I guess it meant GPL v2 at that time. Feel free to upload one if you need it.

**Comment by ebknudsen** [comment]
ah I had completely forgotten about that. GPLv whatever is fine by me (as would MIT or BSD be) , but we should probably ask Osholm as well for good measure. I'm pretty sure he has nothing against it though. Stay tuned.

**Comment by jonwright** [comment]
@osholm - ok for you?

**Comment by osholm** [comment]
@jonwright Yes, that is perfectly fine by me. I guess we just never got around to it :-)

**Comment by ebknudsen** [comment]
Cool - I've now made a PR with GPLv3 - I don't have the proper permissions anymore to pull it in though :-).
Whoever has, may close this lost issue.

**Comment by jonwright** [comment]
Great - thanks - I will try to figure out how to add you write permissions for next time...
(closing this one)
